apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: retail-store
  labels:
    app: cart
    app.kubernetes.io/name: cart
    app.kubernetes.io/part-of: retail-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
        - name: cart
          image: 736508008585.dkr.ecr.ap-southeast-1.amazonaws.com/retail-store/cart:bootstrap
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 256m
              memory: 512Mi
            limits:
              cpu: 512m
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
