apiVersion: v1
kind: Service
metadata:
  name: catalog
  namespace: retail-store
  labels:
    app: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
