apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-promtail
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.16.0
      helm:
        releaseName: promtail
        valueFiles:
          - $values/platform/monitoring/values-promtail.yaml
    - repoURL: https://github.com/tranduyloc895/retail-store-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    retry:
      limit: 5
      backoff: { duration: 30s, maxDuration: 5m, factor: 2 }