apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-storageclass
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  source:
    repoURL: https://github.com/tranduyloc895/retail-store-gitops.git
    targetRevision: main
    path: platform/monitoring
    directory:
      include: "storageclass-gp3.yml"
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: { prune: false, selfHeal: true }   # prune=false vì cluster-scoped