apiVersion: v1
kind: Service
metadata:
  name: cart-dynamodb
  namespace: retail-store
  labels:
    app: cart-dynamodb
    app.kubernetes.io/part-of: retail-store
spec:
  type: ClusterIP
  selector:
    app: cart-dynamodb
  ports:
    - name: dynamodb
      port: 8000
      targetPort: 8000
      protocol: TCP
