{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    release: {{ .Values.monitoring.release }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
    - port: {{ .Values.service.portName }}
      path: {{ .Values.monitoring.path }}
      interval: {{ .Values.monitoring.interval }}
      scrapeTimeout: {{ .Values.monitoring.scrapeTimeout }}
{{- end }}
